const dishList = [
  {
    id: 1,
    img: "https://www.jadlonomia.com/wp-content/uploads/2019/09/IMG_9623_male-600x900.jpg",
    title: "Vegan Pancakes",
    morning: true,
    dayTime: true,
    evening: false,
    vegan: true,
    allergens: ["gluten", "sugar"],
    ingredientsList: [
      "soy milk",
      "vinegar",
      "oil",
      "flour",
      "baking powder",
      "baking soda",
      "salt",
      "aquafaba",
      "sugar",
    ],
  },
  {
    id: 2,
    img: "https://www.jadlonomia.com/wp-content/uploads/2020/03/IMG_3981_male-600x900.jpg",
    title: "Soup for quarantine",
    morning: false,
    dayTime: true,
    evening: true,
    vegan: true,
    allergens: [],
    ingredientsList: ["onion", "carrot", "beans", "cabbage", "tomatoes"],
  },
  {
    id: 3,
    img: "https://www.jadlonomia.com/wp-content/uploads/2012/01/DSC_5852.jpg",
    title: "Banana Bread",
    morning: true,
    dayTime: true,
    evening: true,
    vegan: true,
    allergens: ["gluten", "peanuts", "sugar"],
    ingredientsList: [
      "flour",
      "oil",
      "sugar",
      "soy milk",
      "bananas",
      "baking powder",
      "nuts",
    ],
  },
  {
    id: 4,
    img: "https://www.olgasmile.com/wp-content/uploads/jajecznica-z-serem-i-szczypiorkiem-R-024255.JPG.webp",
    title: "Egg Omelette",
    morning: true,
    dayTime: false,
    evening: false,
    vegan: false,
    allergens: [],
    ingredientsList: ["eggs", "cheese", "onion", "butter", "sour cream"],
  },
]
export default dishList
