const dishList = [
  {
    id: 1,
    img: "https://www.jadlonomia.com/wp-content/uploads/2019/09/IMG_9623_male-600x900.jpg",
    title: "Vegan Pancakes",
    morning: true,
    dayTime: true,
    evening: false,
    havePeanuts: false,
    haveGluten: true,
    haveSugar: true,
    isVegan: true,
    ingredientsList: [
      "soy milk",
      "vinegar",
      "oil",
      "flour",
      "baking powder",
      "baking soda",
      "salt",
      "aquafaba",
      "sugar",
    ],
  },
  {
    id: 2,
    img: "https://www.jadlonomia.com/wp-content/uploads/2020/03/IMG_3981_male-600x900.jpg",
    title: "Soup for quarantine",
    morning: false,
    dayTime: true,
    evening: true,
    havePeanuts: false,
    haveGluten: true,
    haveSugar: true,
    isVegan: true,
    ingredientsList: ["onion", "carrot", "beans", "cabbage", "tomatoes"],
  },
  {
    id: 3,
    img: "https://www.jadlonomia.com/wp-content/uploads/2012/01/DSC_5852.jpg",
    title: "Banana Bread",
    morning: true,
    dayTime: true,
    evening: true,
    havePeanuts: true,
    haveGluten: true,
    haveSugar: true,
    isVegan: true,
    ingredientsList: [
      "flour",
      "oil",
      "sugar",
      "soy milk",
      "bananas",
      "baking powder",
      "nuts",
    ],
  },
  {
    id: 4,
    img: "https://www.olgasmile.com/wp-content/uploads/jajecznica-z-serem-i-szczypiorkiem-R-024255.JPG.webp",
    title: "Egg Omelette",
    morning: true,
    dayTime: false,
    evening: false,
    havePeanuts: false,
    haveGluten: false,
    haveSugar: false,
    isVegan: false,
    ingredientsList: ["eggs", "cheese", "onion", "butter", "sour cream"],
  },
  {
    id: 5,
    img: "https://www.jadlonomia.com/wp-content/uploads/2020/06/IMG_4869_duze1-600x900.jpg",
    title: "Strawberry Pie",
    morning: true,
    dayTime: true,
    evening: false,
    havePeanuts: false,
    haveGluten: true,
    haveSugar: true,
    isVegan: true,
    ingredientsList: [
      "soy milk",
      "vinegar",
      "flour",
      "baking powder",
      "sugar",
      "oil",
      "strawberries",
    ],
  },
  {
    id: 6,
    img: "https://www.jadlonomia.com/wp-content/uploads/2018/01/IMG_4975_male-600x900.jpg",
    title: "Cowboy Soup",
    morning: false,
    dayTime: true,
    evening: true,
    havePeanuts: false,
    haveGluten: false,
    haveSugar: false,
    isVegan: true,
    ingredientsList: [
      "onions",
      "garlic",
      "jalapeno",
      "tomatoes",
      "white kidney beans",
      "red kidney beans",
      "vinegar",
    ],
  },
  {
    id: 7,
    img: "https://www.jadlonomia.com/wp-content/uploads/2018/02/IMG_6111-2_male-600x900.jpg",
    title: "Golden Oatmeal",
    morning: true,
    dayTime: false,
    evening: false,
    havePeanuts: true,
    haveGluten: false,
    haveSugar: true,
    isVegan: true,
    ingredientsList: ["coconut oil", "oats", "sugar", "peanuts"],
  },
  {
    id: 8,
    img: "https://www.olgasmile.com/wp-content/uploads/zupa-ziemniaczana-z-kluskami-R-028544.JPG.webp",
    title: "Potato Soup with Eggs",
    morning: false,
    dayTime: true,
    evening: true,
    havePeanuts: false,
    haveGluten: true,
    haveSugar: false,
    isVegan: false,
    ingredientsList: [
      "potatoes",
      "onions",
      "eggs",
      "flour",
      "parsley",
      "butter",
    ],
  },
  {
    id: 8,
    img: "https://www.olgasmile.com/wp-content/uploads/nalesniki-keto-R-028439.JPG.webp",
    title: "Pancakes Keto",
    morning: true,
    dayTime: true,
    evening: true,
    havePeanuts: false,
    haveGluten: true,
    haveSugar: true,
    isVegan: false,
    ingredientsList: [
      "eggs",
      "sour cream",
      "bamboo fibers",
      "butter",
      "nutella",
    ],
  },
]
export default dishList
